Add file browser
DevinoSolutions/upup pull request #127
Opened 2023-09-13 12:35 UTC by MohamedBechirMejri

2023-09-13 13:56 UTC, bassem97 requested changes
great job !

2023-09-13 13:56 UTC, bassem97 commented on src/UpupUploader.tsx
> +                    googleConfigs={googleConfigs!}
googleConfig may be undefined

2023-09-13 13:56 UTC, bassem97 commented on src/components/UpupUploader/View.tsx
> +import React from 'react'
please remove this

2023-09-13 13:56 UTC, bassem97 commented on src/hooks/useGoogleDrive.ts
> +}
please move this into types/index

2023-09-13 13:56 UTC, bassem97 commented on src/hooks/useGoogleDrive.ts
> +    const [access_token, setAccessToken] = useState<any>(null)
can you please replace the ANYs with the proper type ?

2023-09-13 13:56 UTC, bassem97 commented on src/hooks/useGoogleDrive.ts
> +                                        // @ts-ignore
try to remove the ts-ignore and handle the error please

2023-09-13 13:56 UTC, bassem97 commented on src/hooks/useGoogleDrive.ts
Here's few thing that need to be refactored : 
 - Add JSDoc header for every function especially inside this hook in to explain what it does.
 - Introduce new function to handle the fetch, since we have 3 fetchs with the same headers and url origin.
 - Examinate the return type of every fetch to assign the Types properly.

2023-09-13 14:47 UTC, bassem97 commented
got this when trying to run storybook :

2023-09-13 15:46 UTC, MohamedBechirMejri commented
> got this when trying to run storybook : ![image](https://user-images.githubusercontent.com/36534106/267694522-2e3095e8-bfb0-46a8-be46-4be14c2a22b9.png)

weird, this is what I get 
![image](https://github.com/uNotesOfficial/upup/assets/76930306/1029ba98-8a4c-42cc-a3ca-5d095e97dff3)

2023-09-13 15:46 UTC, MohamedBechirMejri commented
also, tsdx seems to be abandoned. maybe that's causing the build error ?

2023-09-13 15:52 UTC, bassem97 commented
> > got this when trying to run storybook : ![image](https://user-images.githubusercontent.com/36534106/267694522-2e3095e8-bfb0-46a8-be46-4be14c2a22b9.png)
> 
> weird, this is what I get ![image](https://user-images.githubusercontent.com/76930306/267712385-1029ba98-8a4c-42cc-a3ca-5d095e97dff3.png)

try to run story book build

2023-09-13 15:53 UTC, bassem97 commented
this is what i get after signing in : 
![image](https://github.com/uNotesOfficial/upup/assets/36534106/b6e48166-a088-4b18-8515-3170f8374c57)

2023-09-16 04:57 UTC, bassem97 approved these changes
Good stuff

2023-09-16 04:58 UTC, merged